### ISSUE TITLE
plot_boxplot() color by group?

### ISSUE THREAD

**Issue by arbet003** [boxuancui/DataExplorer#167] opened 2022-03-21 17:51 UTC
Hello,

When using `plot_boxplot()`, is it possible to color the boxplots by group?   I know how to do this in ggplot, see example code below:

```
library(DataExplorer)
library(tidyverse)

data(mtcars)
mtcars <- mtcars %>% 
  mutate(
    cyl = as.factor(cyl)
  )

# boxplot fill color by cyl
ggplot(data=mtcars, aes(x=cyl, y=hp, fill=cyl))+
  geom_boxplot()
```

![image](https://user-images.githubusercontent.com/16568477/159333349-951cf937-ee63-45d3-97f7-eaec3f3c9e44.png)

When using `plot_boxplot()`, all of the boxplots are white... how can I fill/color the boxes by a grouping variable ("cyl")?

```
plot_boxplot(data=mtcars, by="cyl")
```

![image](https://user-images.githubusercontent.com/16568477/159333766-543a7bfb-1099-4653-baec-28599490d62e.png)

**Comment by boxuancui** [comment] 2022-03-21 18:18
Hi @arbet003 I did not enable coloring for this type of plots, and it is by design. Here, you are already plotting against `cyl` column, so it will naturally be broken out in the chart. Any additional action (adding color in this case) will be redundant and provide duplicate of information. Just imagine if this is some other dataset with many more categories, it will be very hard to visualize what was meant to.

**Closed as completed by boxuancui** 2022-03-21 18:18 UTC
Labels: N/A: nothing to do here
