### ISSUE TITLE
Histogram bug

### ISSUE THREAD

**Issue by jcflyingco** [boxuancui/DataExplorer#65] opened 2018-04-21 04:18 UTC
library(DataExplorer)
create_report(airquality)

Day variable  count  is incorrect on Histogram 

![2018-04-21 12_16_50-clipboard](https://user-images.githubusercontent.com/28838467/39080303-ee2ffa78-455d-11e8-9897-db671f28a269.jpg)

**Comment by StatsRhian** [comment] 2018-04-23 14:28
Hi @jcflyingco, I think that this is just due to way that the bins have been selected in `geom_histogram.` 
In my opinion, both `Month` and `Day` should not be treated as a continuous variable, therefore histograms are not appropriate here. 

E.g. 

```
library(DataExplorer)
library(tidyverse)

airquality %>%
  mutate(Day = as.factor(Day)) %>%
  mutate(Month = as.factor(Month)) %>%
create_report()
```

**Comment by boxuancui** [comment] 2018-04-23 16:05
I agree with @trianglegirl . One purpose of this package is to let you identify columns like these as quickly as possible, and make appropriate treatment, e.g., `as.factor`.

With that said, `plot_histogram` calls `geom_histogram` directly. You may always customize the bins if necessary.

    plot_histogram(airquality$Day, binwidth = 0.5)

I understand the frustrations from the inability to customize reports, so I created #41 for v0.6. Before that, you can only customize the report template and hack around it.

Finally, closing this ticket since it is not a bug. Thank you all!

**Closed as completed by boxuancui** 2018-04-23 16:05 UTC
Labels: N/A: wontfix
